<?php
    // TODO: add forward slash to the root path at the end if not present
    // TODO: add graphics path in admin and default it to external indicator folder with old and new indicators

    $helper = $this->helper('WebRotate360\ProductViewerStandard\Helper\Data');
    if (!$helper)
        return;

    $rootPath   = $helper->getWebrotateRootUrl();
    $configPath = $helper->getWebrotatePath();
    $swatches   = $helper->getSwatches();

    if (empty($configPath))
    {
        $configPath = $helper->getMasterConfigUrl();
        if (!empty($configPath))
            $isMasterMode = true;
    }

    $isLoaderOn = (!isset($isMasterMode) && !empty($configPath)) || (isset($isMasterMode) && !empty($rootPath));
?>

<?php if ($isLoaderOn): ?>
    <?php $configPath = $helper->getBaseUrl() . $configPath; ?>
    <link  rel="stylesheet" type="text/css" href="<?php echo $helper->getViewerSkinUrl() ?>" />
    <script language="javascript" type="text/javascript">
        var __WR360Config =  {
            thumbPath: "<?php echo $helper->getPopupIconUrl() ?>",
            graphicsPath: "<?php echo $helper->getGraphicsPathUrl() ?>",
            endPlacement: <?php $helper->isEndPlacement() ? print("true") : print("false") ?>,
            confFileURL: "<?php echo $configPath ?>",
            rootPath: "<?php echo $rootPath ?>",
            licensePath: "<?php echo $helper->getLicense() ?>",
            useAnalytics: <?php $helper->isUseAnalytics() ? print("true") : print("false") ?>,
            apiCallback: "<?php echo $helper->getApiCallback() ?>",
            swatches: <?php $swatches ? print($swatches) : print("null") ?>
        };
    </script>
<?php endif?>
