<?php
// TODO: add forward slash to the root path at the end if not present
// TODO: add graphics path in admin and default it to external indicator folder with old and new indicators

/** @var WebRotate360\ProductViewerStandard\ViewModel\WebRotatedStandard $viewModel */
$viewModel = $block->getViewModel();

$rootPath = $viewModel->getWebrotateRootUrl();
$configPath = $viewModel->getWebrotatePath();
$swatches = $viewModel->getSwatches();

if (empty($configPath)) {
    $configPath = $viewModel->getMasterConfigUrl();
    if (!empty($configPath)) {
        $isMasterMode = true;
    }
}

$configUrl = $viewModel->getBaseUrl();
if ($viewModel->getUseMediaUrlConfig() === true) {
    $configUrl = $viewModel->getMediaUrl();
}

$isLoaderOn = (!isset($isMasterMode) && !empty($configPath)) || (isset($isMasterMode) && !empty($rootPath));
?>

<?php if ($isLoaderOn): ?>
    <?php $configPath = $configUrl . $configPath; ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $viewModel->getViewerSkinUrl() ?>"/>
    <script language="javascript" type="text/javascript">
        var __WR360Config = {
            thumbPath: "<?php echo $viewModel->getPopupIconUrl() ?>",
            graphicsPath: "<?php echo $viewModel->getGraphicsPathUrl() ?>",
            endPlacement: <?php $viewModel->isEndPlacement() ? print("true") : print("false") ?>,
            confFileURL: "<?php echo $configPath ?>",
            rootPath: "<?php echo $rootPath ?>",
            licensePath: "<?php echo $viewModel->getLicense() ?>",
            useAnalytics: <?php $viewModel->isUseAnalytics() ? print("true") : print("false") ?>,
            apiCallback: "<?php echo $viewModel->getApiCallback() ?>",
            swatches: <?php $swatches ? print($swatches) : print("null") ?>
        };
    </script>
<?php endif ?>

